### ISSUE TITLE
Allows population of dependency_overrides

### ISSUE THREAD

**Issue by jonasfj** [google/mono_repo.dart#117]
In many mono_repo setups we have a sibling packages that depends on each others.

It would be neat there was a command to generate a `dependency_overrides` for dependencies that are siblings packages.

I'm not sure how this would work, we'll probably need a command to add/remove the dependency overwrites, unless pub ignores them when publishing packages.

**Comment by kevmoo** [comment]
PRs welcome. 😄

**Comment by devoncarew** [comment]
With the introduction of the `pubspec_overrides.yaml` file, this issue is likely obsolete?

**Comment by jakemac53** [comment]
Yes I think we can close this, use pubspec_overrides.yaml instead.
