### ISSUE TITLE
Enable windows tests (and get them passing)

### ISSUE THREAD

**Issue by jakemac53** [google/mono_repo.dart#175]
We now support multiple oses, but a lot of the tests fail on windows for various (mostly not scary) reasons.

**Comment by kevmoo** [comment]
@jakemac53 – I think we can close this, right?

**Comment by jakemac53** [comment]
We still don't run them on windows actually

**Comment by jakemac53** [comment]
But, we could close as not planned

**Comment by kevmoo** [comment]
https://github.com/google/mono_repo.dart/runs/1494384260?check_suite_focus=true
?

**Comment by jakemac53** [comment]
Oh! did you just add those?

**Comment by kevmoo** [comment]
> Oh! did you just add those?

been there for a bit – don't remember
