### ISSUE TITLE
Consider also supporting github actions as a CI.

### ISSUE THREAD

**Issue by devoncarew** [google/mono_repo.dart#192]
Github actions is another useful CI (in addition to travis). It would be worth seeing what the required work would be to support  github actions here.

**Comment by kevmoo** [comment]
we could add a `mono_repo github` command – to mimic the `travis` command that currently exists...

**Comment by kevmoo** [comment]
the nice thing about the current configuration of `mono_repo` – as a mono repo – is that it's easy to test with itself!

**Comment by jakemac53** [comment]
Right we could pretty easily run both travis and github actions on this repo

**Comment by kevmoo** [comment]
WIP 😄

**Comment by kevmoo** [comment]
This is in beta, so closing. Hoping for a stable release soonish – but would love folks to try it out!
