### ISSUE TITLE
Mark .github/workflows/dart.yml as generated to collapse in github diff view

### ISSUE THREAD

**Issue by natebosch** [google/mono_repo.dart#307]
These files often have noisy changes, and they always show up at the very top of the diff in a PR.

I'm not sure if there is a comment we can stick in the file so that github knows it is generated. The other option is to create a `.gitattributes` file with

```
.github/workflows/dart.yml linguist-generated=true
```

If we also add a line with `-diff` it will also suppress it from local `git diff` commands, and adding `-merge` will make it pick the latest on merge instead of introducing merge conflict markers. This is probably better for this file since we'd never want to manually resolve conflicts anyway, we'd just regenerate it.

```
.github/workflows/dart.yml -diff -merge
.github/workflows/dart.yml linguist-generated=true
```

We could probably generate the `.gitattributes` file for users if it doesn't already exist. Not sure what we'd want to do if that file already exists. We could put in lines for all generated files.

**Comment by kevmoo** [comment]
I wonder if GitHub detects something here?

could we try adding `# Generated by mono-repo...etc etc` at the top and see
if it's picked up/

**Comment by natebosch** [comment]
These are collapsed in github today.
