### ISSUE TITLE
Run PR tests merged with master instead of on PR branch

### ISSUE THREAD

**Issue by jakemac53** [google/mono_repo.dart#308]
I haven't confirmed fully but it appears that the tests run at the PR head commit and not after merging with master.

It is generally much safer to run in a state that is merged with master as it helps eliminate race conditions - at least at the time the tests run you know it was up to date with master regardless of the state of the authors branch.

**Comment by kevmoo** [comment]
Would you clarify, @jakemac53 ? Is this an issue?

**Comment by natebosch** [comment]
We use `actions/checkout` which will use the merge commit by default. We'd have to specifically configure it to use the pr HEAD commit if that was what we wanted (which we don't) - https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
