### ISSUE TITLE
"mono_repo pub get" issue with flutter package 

### ISSUE THREAD

**Issue by BenVercammen** [google/mono_repo.dart#313]
So I have this mono_repo project where most packages are pure dart packages, and one is a flutter package.
When I use the `mono_repo pub get` command, the flutter package fails with the following error:

```
Starting `flutter packages get` in `my_flutter_package`...
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: flutter packages get
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      pub (package:mono_repo/src/commands/pub.dart:113:32)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#4      MonoRepoRunner.runCommand (package:mono_repo/src/runner.dart:55:5)
<asynchronous suspension>
#5      main (file:///C:/Users/____/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/mono_repo-3.4.7/bin/mono_repo.dart:15:5)
<asynchronous suspension>
```

I've taken the snippet from the `command/pub.dart` file that executes the `Process.start(...)` part, and it turns out that I can fix the exception by setting the `executable` value to the full path to the flutter executable (ie:  `C:\\Tools\\Flutter\\flutter_windows_1.20.4-stable\\flutter\\bin\\flutter.bat`) instead of just `flutter`.

I do have the "flutter" bin folder on my classpath, so when I run the command from the terminal (command prompt on windows) it works as expected.

Now, for my question(s): what am I missing here? Why doesn't the dart:io Process pick up the flutter command from my classpath? And why is the `pubPath` a full path while `flutter` command is not?

I know this probably isn't really a mono_repo issue, and maybe the answer is pretty straightforward, but I'm stuck on this one for a while already and I suppose this might serve as documentation for someone else later on...

**Comment by kevmoo** [comment]
It *is* a mono_repo problem. See https://github.com/google/mono_repo.dart/issues/45

**Comment by BenVercammen** [comment]
Okay, so it's still an open issue? I've been looking but can't seem to find any merged PR's for it. 

I'm willing to contribute as well, just wondering which direction I should go. For now I can only think of checking for a `%FLUTTER_HOME%` env variable to find the full path to flutter SDK, before falling back to the regular "flutter" path/command.
