### ISSUE TITLE
"dart.bat" file not found (anymore)

### ISSUE THREAD

**Issue by BenVercammen** [google/mono_repo.dart#357]
So after updating both flutter and mono_repo, I can no longer do ``[dart] pub global run mono_repo pub get``.
If I am not mistaken, it turns out **mono_repo** is explicitly calling ``dart.bat`` when on windows.

Apparently, in the Dart SDK folder (using Flutter, so ``...\flutter\bin\cache\dart-sdk\bin``), I no longer have a ``dart.bat`` file.
Files that **are** present:
 - ``dart.exe``
 - ``dart.lib``
 - ``dart2js.bat``
 - ``dartanalyzer.bat``
 - ``dartaotruntime.exe``
 - ``dartdevc.bat``
 - ``dartdoc.bat``
 - ``pub.bat``

Was using flutter **2.8.0-3.2.pre** (.bat file already gone) and just upgraded to **2.9.0-0.1.pre**. Haven't been using mono_repo for a couple of months as I was working on some other projects, so I have no idea at which point in time this stopped working.

@kevmoo Do you happen to be aware of changes to Flutter/Dart SDK along those lines? For some reason I assume you are quite knowledgeable on these things. It would take me quite some time to go digging through changelogs and the likes to pin down the exact versions of both Flutter/Dart SDK and mono_repo when this would have stopped working, so I'm hoping you already have an idea about this?

My guess would be that the Dart SDK included with Flutter used to contain a ``dart.bat`` file but for some reason doesn't do that anymore. Not sure if ``dart.exe`` came in its place or has always been there before?

Anyhow, I assume that modifying the bottom lines of ``lib/src/commands/pub.dart``, containing the platform check (``Platform.isWindows ? 'dart.bat' : 'dart'``) would probably resolve the issue for me.

However, I'm not sure if my assumptions about the Dart SDK are valid, and whether or not that would break stuff for people using older versions?

**Edit:** just found out that there is a file ``.../flutter/bin/dart.bat``, but mono_repo is referring to:
`` Starting `C:\...\flutter\bin\cache\dart-sdk\bin\dart.bat pub get` ``,
while maybe it should become 
`` Starting `C:\...\flutter\bin\dart.bat pub get` ``
?

**Comment by jakemac53** [comment]
Interesting, we generally assume the layout of the dart_sdk is identical between the flutter and dart sdks (effectively we assume flutter is just shipping an unmodified dart sdk).

We have other tools as well that rely on this location, can start doing some digging.

**Comment by jakemac53** [comment]
Or possibly we should just always be calling the exe file, I think most tools have actually migrated to that but I could be wrong.

**Comment by jakemac53** [comment]
I actually don't see a `dart.bat` shipped with the dart sdk either, even going back to 2.14.0. So it seems like this has not existed for a while, likely since the unified `dart` tool was added?
