### ISSUE TITLE
Flutter package determination

### ISSUE THREAD

**Issue by dnys1** [google/mono_repo.dart#397]
The current determination for whether the package is a Dart or Flutter package is:

```dart
  bool get usesFlutter =>
      _dependsOnFlutterSdk || _dependsOnFlutterPackage || _hasFlutterKey;
```

So, a package with no Flutter dependency or SDK constraint with a `flutter` key in the YAML is treated as a Flutter package. I have a Dart package which includes an `assets` specifier for when it's a dependency of a Flutter package. 

This is kind of a weird setup and I may be abusing the tooling here. Just wanted to understand the context for the last check and see if my use case should be treated differently or not. Thanks!

**Comment by kevmoo** [comment]
Hrm...I guess I could look to see what the `pub` client does here. Hold a sec...

**Comment by kevmoo** [comment]
Yup. Looks like we can remove the `_hasFlutterKey` check. Seems we're over constrained!

**Comment by kevmoo** [comment]
PR out for review!

**Comment by dnys1** [comment]
Fastest PR in the west :D Thanks!
