### ISSUE TITLE
The save-state command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by techouse** [google/mono_repo.dart#421]
Hi,

I just got this message from one of my workflows using `mono_repo` complaining about the `save-state` command being deprecated

> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by JEuler** [comment]
👍

**Comment by kevmoo** [comment]
I don't think mon_repo uses `save-state` anywhere. Sure this is not in your configuration?

**Comment by techouse** [comment]
I think the problem lies in the pinned version of [actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b](https://github.com/actions/checkout/commit/2541b1294d2704b0964813337f33b291d3f8596b) which `mono_repo` uses in the generated Github action Dart CI YAML file.

That points to `actions/checkout@v3.0.2`, however, it looks like the fix for `saveState` and `getState` came in version [`actions/checkout@v3.1.0`](https://github.com/actions/checkout/blob/main/CHANGELOG.md#v310)

Here's a [related issue](https://github.com/actions/checkout/issues/959) in actions/checkout.
