### ISSUE TITLE
add a mono_repo.yaml option to not generate the self-check

### ISSUE THREAD

**Issue by devoncarew** [google/mono_repo.dart#446]
- add a mono_repo.yaml option to not generate the self-check

This would be an alternative to https://github.com/google/mono_repo.dart/pull/420; a way for us to leverage dependabot for repos that use mono_repo. Currently every dependabot would fail the CI as the self-check workflow of mono_repo will turn red.

**Comment by kevmoo** [comment]
Well, self check is ALREADY an option. We want an option to say "don't check the action versions" – which is more specific.

**Comment by kevmoo** [comment]
Maybe check that all of the versions of a given action are the same? 🤷

**Comment by jakemac53** [comment]
I do think disabling this check entirely would be a mistake, it is very easy to forget to regenerate it and this has saved me many times

**Comment by devoncarew** [comment]
closing in favor of https://github.com/google/mono_repo.dart/issues/451
