### ISSUE TITLE
Support packages using flutter SDK 

### ISSUE THREAD

**Issue by johnpryan** [google/mono_repo.dart#45]
we have a mono_repo with both flutter, web, and pure dart packages. when we run "mono_repo check" we get this error:

```
mono_repo check
Unhandled exception:
Invalid argument (data): No clue how to deal with `{sdk: flutter}`.: Instance of 'YamlMap'
```

**Comment by kevmoo** [comment]
Good catch!

**Comment by kevmoo** [comment]
@johnpryan – pull requests welcome!

**Comment by rrousselGit** [comment]
I'm interesting in working on this. 
But what is the expected behaviour ?

**Comment by kevmoo** [comment]
I think our `pubspec` parser just chokes on the `sdk: flutter` bit in a package.

I *think* it'd just be a matter of ignoring those type of entries.

**Comment by rrousselGit** [comment]
Considering flutter comes with it's own set of tools for builds/test/packages I don't think we can just ignore it.

After all we don't `pub get` in flutter. We `flutter pub get`. 
And maybe there's some stuff to do on travis too.

**Comment by kevmoo** [comment]
Right. There will be work to get all of the bits working...the pubspec parsing is likely just a start...

**Comment by rrousselGit** [comment]
Submitted a pull request that should remove this error. https://github.com/dart-lang/mono_repo/pull/58

But it should still not work with flutter yet. Simply parsing sdk will still make `mono_repo pub get` crash.
