### ISSUE TITLE
update mono_repo so that it can work with dependabot

### ISSUE THREAD

**Issue by devoncarew** [google/mono_repo.dart#451]
Currently repos that use both mono_repo and turn on the option to validate the mono_repo config on the CI don't work with dependabot; all the dependabot created PRs - that bump a github action version - will fail on the mono_repo validate step.

We should figure out a way to get these two systems to work together.

**Comment by devoncarew** [comment]
https://github.com/google/mono_repo.dart/pull/420 is one possible solution here - have the validation be independent of the action versions in the generated workflow file.

**Comment by jakemac53** [comment]
+1 for #420 - lets re-open it?

**Comment by jakemac53** [comment]
This should be done now, to enable it for a repo you will need to update to the latest mono_repo and regenerate your configs so the `--validate` step uses the new logic.
