### ISSUE TITLE
Add (or document?) the ability to add arguments to `flutter test`

### ISSUE THREAD

**Issue by domesticmouse** [google/mono_repo.dart#493]
For https://github.com/domesticmouse/devfest_2024 I need the ability to augment `flutter test` with the `--enable-impeller` flag, because `flutter_gpu` doesn't work without it.

**Comment by jakemac53** [comment]
Here is an example of how to pass arguments to the test command https://github.com/dart-lang/build/blob/master/_test/mono_pkg.yaml#L18.

Note that in general this package is pretty much self service - so if you want a new feature you will have to contribute it. 

The docs are also quite lacking, you pretty much just have to look at example repos for the more complex setups (PRs are also welcome though if you find something undocumented!)
